<!--
Copyright: Ankitects Pty Ltd and contributors
License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
-->
<script lang="ts">
    import { onMount } from "svelte";

    import type { PageData } from "./$types";
    // A build-time snapshot of docs/eval-artifacts (generated by testdeck/build_report.py),
    // bundled into the page so the Evidence panel also works on AnkiDroid, which has no
    // /_anki/speedrunEvidence endpoint and no artifacts folder. Desktop still prefers the
    // live endpoint; this is the fallback.
    import bundledEvidence from "./evidence-data.json";

    // Shape of the `speedrunDashboard` RPC response (see backend contract).
    // Declared locally so this read-only page type-checks against the contract
    // even before the generated protobuf types land on the backend track.
    interface SpeedrunSection {
        section: string;
        abbrev: string;
        coverage: number;
        memory?: number;
        memoryLow?: number;
        memoryHigh?: number;
        reviewedCards?: number;
        performance?: number;
        performanceLow?: number;
        performanceHigh?: number;
        performanceItems?: number;
        topics?: { code: string; title: string; covered: boolean }[];
    }

    interface SpeedrunPlanItem {
        code: string;
        title: string;
        rung: string;
        reason: string;
        score: number;
        prerequisite: boolean;
    }

    interface SpeedrunEvidence {
        memoryLogLoss?: number;
        memoryRmse?: number;
        memoryReviews?: number;
        perfAucFull?: number;
        perfAucRecall?: number;
        perfAucDelta?: number;
        perfResponses?: number;
        perfPassed?: boolean;
    }

    interface SpeedrunDashboardData {
        overallCoverage: number;
        coveredLeaves: number;
        totalLeaves: number;
        sections: SpeedrunSection[];
        readinessAllowed: boolean;
        giveUpLine: number;
        totalReviews: number;
        performanceStatus: string;
        readinessStatus: string;
        plan: SpeedrunPlanItem[];
        evidence?: SpeedrunEvidence;
    }

    export let data: PageData;

    // All fields treated as optional so an empty collection (no MCAT cards)
    // renders gracefully instead of throwing.
    $: dashboard = (data.data ?? {}) as Partial<SpeedrunDashboardData>;

    $: overallCoverage = dashboard.overallCoverage ?? 0;
    $: coveredLeaves = dashboard.coveredLeaves ?? 0;
    $: totalLeaves = dashboard.totalLeaves ?? 0;
    $: sections = dashboard.sections ?? [];
    $: plan = dashboard.plan ?? [];
    $: readinessAllowed = dashboard.readinessAllowed ?? false;
    $: giveUpPct = Math.round((dashboard.giveUpLine ?? 0.5) * 100);
    $: totalReviews = dashboard.totalReviews ?? 0;
    $: isEmpty = sections.length === 0 && plan.length === 0;

    function pct(value: number): string {
        return `${Math.round(value * 100)}%`;
    }

    function fmtPct(value?: number): string {
        return value == null ? "\u2013" : `${Math.round(value * 100)}%`;
    }

    function fmt(value?: number, digits = 3): string {
        return value == null ? "\u2013" : value.toFixed(digits);
    }

    $: evidence = dashboard.evidence;
    $: hasMemoryEvidence = evidence?.memoryRmse != null;
    $: hasPerfEvidence = (evidence?.perfResponses ?? 0) > 0;

    // Step 3 (turn performance into a score + range) - the DOCUMENTED method (see
    // docs/score-mapping.md). Each covered section's held-out performance accuracy maps to
    // its MCAT section scaled-score band [118, 132]; the four section scores sum to the
    // total scale [472, 528]. Sections with no performance data yet (e.g. CARS, out of
    // scope) are imputed at the mean of the covered sections, so the total stays on-scale;
    // this imputation is stated explicitly. The range is the sum of the sections' Wilson
    // performance bounds (same imputation). Shown only when readiness is allowed AND
    // performance has graded data. This is a display-layer index derived from the engine's
    // validated performance - it is NOT validated against real MCAT results (Step 4).
    const MCAT_MIN = 472;
    const MCAT_MAX = 528;
    const SECTION_MIN = 118;
    const SECTION_MAX = 132;
    const N_SECTIONS = 4;

    interface Projected {
        score: number;
        low: number;
        high: number;
        coveredSections: number;
    }

    function toSection(acc: number): number {
        return SECTION_MIN + acc * (SECTION_MAX - SECTION_MIN);
    }

    function computeProjected(): Projected | null {
        if (!readinessAllowed) return null;
        const scored = sections.filter(
            (s) => s.performance != null && (s.performanceItems ?? 0) > 0,
        );
        if (!scored.length) return null;
        // Per-section scaled scores + Wilson bounds, equal-weighted (each section band is
        // equal on the MCAT scale), then impute uncovered sections at the covered mean.
        let sum = 0;
        let lo = 0;
        let hi = 0;
        for (const s of scored) {
            sum += toSection(s.performance as number);
            lo += toSection(s.performanceLow ?? (s.performance as number));
            hi += toSection(s.performanceHigh ?? (s.performance as number));
        }
        const missing = Math.max(0, N_SECTIONS - scored.length);
        const meanScore = sum / scored.length;
        const meanLo = lo / scored.length;
        const meanHi = hi / scored.length;
        const clamp = (v: number) => Math.round(Math.min(MCAT_MAX, Math.max(MCAT_MIN, v)));
        return {
            score: clamp(sum + missing * meanScore),
            low: clamp(lo + missing * meanLo),
            high: clamp(hi + missing * meanHi),
            coveredSections: scored.length,
        };
    }

    $: projected = computeProjected();

    // User-facing copy built from the numbers (no engine jargon). MIN_REVIEWS mirrors
    // the engine's readiness review floor.
    const MIN_REVIEWS = 200;
    $: hasPerformance = sections.some((s) => s.performance != null);

    // The student's own aggregate recall / accuracy (weighted by how much backs each),
    // so the copy can say how they're doing rather than define the metric.
    function weightedMean(
        value: (s: SpeedrunSection) => number | null | undefined,
        weight: (s: SpeedrunSection) => number,
    ): number | null {
        let sum = 0;
        let w = 0;
        for (const s of sections) {
            const v = value(s);
            const wt = weight(s);
            if (v == null || wt <= 0) continue;
            sum += v * wt;
            w += wt;
        }
        return w > 0 ? sum / w : null;
    }

    $: memAgg = weightedMean((s) => s.memory, (s) => s.reviewedCards ?? 0);
    $: perfAgg = weightedMean((s) => s.performance, (s) => s.performanceItems ?? 0);

    interface Reading {
        tone: "live" | "warn" | "lock";
        chip: string;
        text: string;
    }

    $: memoryReading = ((): Reading => {
        if (memAgg == null) {
            return { tone: "lock", chip: "Locked", text: "Study some cards to start measuring your recall." };
        }
        if (memAgg >= 0.9) {
            return { tone: "live", chip: "Strong", text: "You're holding onto what you've studied - keep up regular reviews to stay here." };
        }
        if (memAgg >= 0.8) {
            return { tone: "live", chip: "Good", text: "Solid recall - a little more review will lock it in." };
        }
        if (memAgg >= 0.65) {
            return { tone: "warn", chip: "Fair", text: "Your recall is shaky - review more often to strengthen it." };
        }
        return { tone: "warn", chip: "Weak", text: "Recall is low - make daily review a priority." };
    })();

    $: performanceReading = ((): Reading => {
        if (perfAgg == null) {
            return { tone: "lock", chip: "Locked", text: "Answer some exam-style questions to measure this." };
        }
        if (perfAgg >= 0.75) {
            return { tone: "live", chip: "Strong", text: "You handle new, exam-style questions well - keep it up." };
        }
        if (perfAgg >= 0.6) {
            return { tone: "live", chip: "Good", text: "Doing well on new questions - keep practicing to push higher." };
        }
        if (perfAgg >= 0.45) {
            return { tone: "warn", chip: "Fair", text: "About half right on exam-style questions - more application practice will help." };
        }
        return { tone: "warn", chip: "Weak", text: "Application is the weak spot - focus your practice on exam-style questions." };
    })();

    $: readinessReading = ((): Reading => {
        if (!projected) {
            if (readinessAllowed) {
                return { tone: "live", chip: "Tracking", text: "You've studied enough to start projecting your MCAT score range - answer some exam-style questions to get a number." };
            }
            return {
                tone: "lock",
                chip: "Locked",
                text: `So far ${pct(overallCoverage)} of ${giveUpPct}% coverage and `
                    + `${totalReviews.toLocaleString()} of ${MIN_REVIEWS} reviews - keep studying to unlock this.`,
            };
        }
        const s = projected.score;
        if (s >= 512) {
            return { tone: "live", chip: "Competitive", text: `A projected ${s} is in a competitive range - you're in strong shape; keep it steady.` };
        }
        if (s >= 502) {
            return { tone: "live", chip: "On track", text: `A projected ${s} is above the midpoint of the MCAT scale - a solid base; more study can push it higher.` };
        }
        if (s >= 492) {
            return { tone: "warn", chip: "Building", text: `A projected ${s} is around the middle of the range (472-528) - keep studying to climb.` };
        }
        return { tone: "warn", chip: "Early", text: `A projected ${s} is below the midpoint - more study should move this up.` };
    })();
    // -- In-app evaluation evidence (spec 7 / 8 / 9 / 10) ----------------------
    // Fetches the same artifacts docs/eval-results.md is generated from (via the
    // speedrun_evidence post handler) and renders them inline, charts and all.
    let evalResults: any = null;
    let showEvidence = false;
    let evidenceLoading = false;
    let evidenceError = "";

    async function loadEvidence(): Promise<void> {
        evidenceLoading = true;
        evidenceError = "";
        try {
            // Desktop: mediasrv serves live artifacts from docs/eval-artifacts (the CSRF
            // guard wants application/binary; the handler ignores the body and returns JSON).
            const res = await fetch("/_anki/speedrunEvidence", {
                method: "POST",
                headers: { "Content-Type": "application/binary" },
                body: new Uint8Array(),
            });
            if (!res.ok) throw new Error(`HTTP ${res.status}`);
            const data = await res.json();
            // A packaged build with no artifacts folder reports available:false - use the
            // bundled snapshot in that case too.
            evalResults = data && data.available ? data : bundledEvidence;
            showEvidence = true;
        } catch (e) {
            // Mobile (AnkiDroid) has no speedrunEvidence endpoint, so fall back to the
            // snapshot bundled into the shared page at build time.
            evalResults = bundledEvidence;
            showEvidence = true;
        } finally {
            evidenceLoading = false;
        }
    }

    async function toggleEvidence(): Promise<void> {
        if (evalResults) {
            showEvidence = !showEvidence;
            return;
        }
        await loadEvidence();
    }

    // Evidence stays hidden by default (desktop + mobile); the toggle loads it on the
    // first click, then shows/hides it.

    // Render our own trusted artifact strings: escape, then **bold** and `code`.
    function md(s: string): string {
        const esc = String(s)
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;");
        return esc
            .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
            .replace(/`(.+?)`/g, "<code>$1</code>");
    }

    // -- Host bridge: the dashboard as the app's home + study loop -----------------
    // Desktop exposes window.pycmd (Qt web-channel); AnkiDroid has no pycmd, so we POST to
    // a /_anki route the SpeedrunPage handler intercepts. hasBridge (desktop) gates the
    // desktop-only Decks/Tools affordances (mobile navigates via its drawer + back button).
    let hasBridge = false;

    onMount(() => {
        const check = () => (hasBridge = typeof (window as any).pycmd === "function");
        check();
        if (!hasBridge) setTimeout(check, 400); // pycmd is injected asynchronously
    });

    function hostAction(desktopCmd: string, mobilePath: string, body = ""): void {
        const w = window as any;
        if (typeof w.pycmd === "function") {
            w.pycmd(`speedrun:${desktopCmd}`);
        } else {
            fetch(`/_anki/${mobilePath}`, {
                method: "POST",
                headers: { "Content-Type": "application/binary" },
                body: new TextEncoder().encode(body),
            }).catch(() => {});
        }
    }

    // Start a focused review session for one topic - the core Speedrun loop.
    function studyTopic(code: string): void {
        hostAction(`studyTopic:${code}`, "speedrunStudyTopic", code);
    }
    // "Study now" studies the single best next thing (top of the plan).
    function studyNext(): void {
        if (plan.length) studyTopic(plan[0].code);
    }
    function openDecks(): void {
        hostAction("decks", "speedrunDecks");
    }
    function openTools(): void {
        hostAction("hub", "speedrunTools");
    }
    function loadStarterDeck(): void {
        hostAction("seed", "speedrunSeed");
    }
</script>

<div class="speedrun">
    <header class="head">
        <h1>Speedrun</h1>
        <div class="head-actions">
            {#if !isEmpty && plan.length}
                <button class="study-now" on:click={studyNext}>Study now</button>
            {/if}
            {#if hasBridge}
                <button class="head-btn" on:click={openDecks} title="Go to your Anki decks">Decks</button>
                <button
                    class="head-btn gear"
                    on:click={openTools}
                    title="Speedrun tools & settings"
                    aria-label="Speedrun tools and settings"
                >&#9881;</button>
            {/if}
            <button class="evidence-toggle" on:click={toggleEvidence}>
                {#if evidenceLoading}Loading...{:else if showEvidence}Hide evidence{:else}Evidence & eval results{/if}
            </button>
        </div>
    </header>

    {#if isEmpty}
        <div class="onboarding">
            <h2>Welcome to Speedrun</h2>
            <p>
                Your MCAT command center. Load the starter deck to see your coverage, memory,
                and a study plan - then just press <strong>Study now</strong> and keep going.
            </p>
            {#if hasBridge}
                <button class="study-now" on:click={loadStarterDeck}>Load the MCAT starter deck</button>
            {:else}
                <p class="muted">
                    On your phone, sync from the desktop app (which holds your MCAT deck) to get
                    started - your scores and plan then appear here automatically.
                </p>
            {/if}
        </div>
    {/if}

    <div class="panels">
        <section class="panel coverage">
            <h2>Coverage</h2>
            <div class="coverage-head">
                <span class="big">{pct(overallCoverage)}</span>
                {#if readinessAllowed}
                    <span class="pill ok">On track</span>
                {:else}
                    <span class="pill no">Keep studying</span>
                {/if}
            </div>
            <div class="cov-track" aria-hidden="true">
                <span class="cov-fill" style="width: {pct(overallCoverage)}"></span>
            </div>
            <div class="leaves">
                {coveredLeaves} of {totalLeaves} topics covered
            </div>

            {#if sections.length}
                <table>
                    <thead>
                        <tr>
                            <th scope="col" class="section-cell">Section</th>
                            <th scope="col" class="num">Covered</th>
                            <th class="bar" aria-hidden="true"></th>
                            <th scope="col" class="num mem">Memory</th>
                            {#if hasPerformance}
                                <th scope="col" class="num mem">Performance</th>
                            {/if}
                        </tr>
                    </thead>
                    <tbody>
                        {#each sections as s}
                            <tr>
                                <td class="section-cell">
                                    <abbr title={s.section}>{s.abbrev}</abbr>
                                </td>
                                <td class="num">{pct(s.coverage)}</td>
                                <td class="bar" aria-hidden="true">
                                    <div class="track">
                                        <span style="width: {pct(s.coverage)}"></span>
                                    </div>
                                </td>
                                <td
                                    class="num mem"
                                    title={s.reviewedCards
                                        ? `${s.reviewedCards} reviewed cards`
                                        : "no reviewed cards yet"}
                                >
                                    {#if s.memory == null}
                                        <span class="dash">&mdash;</span>
                                    {:else}
                                        <span class="mem-point">{pct(s.memory)}</span>
                                        {#if s.memoryLow != null && s.memoryHigh != null}
                                            <span class="mem-range">
                                                {pct(s.memoryLow)}&ndash;{pct(s.memoryHigh)}
                                            </span>
                                        {/if}
                                    {/if}
                                </td>
                                {#if hasPerformance}
                                    <td
                                        class="num mem"
                                        title={s.performanceItems
                                            ? `${s.performanceItems} answered items`
                                            : "no answered exam-style items yet"}
                                    >
                                        {#if s.performance == null}
                                            <span class="dash">&mdash;</span>
                                        {:else}
                                            <span class="mem-point">{pct(s.performance)}</span>
                                            {#if s.performanceLow != null && s.performanceHigh != null}
                                                <span class="mem-range">
                                                    {pct(s.performanceLow)}&ndash;{pct(s.performanceHigh)}
                                                </span>
                                            {/if}
                                        {/if}
                                    </td>
                                {/if}
                            </tr>
                        {/each}
                    </tbody>
                </table>
                <details class="topics">
                    <summary>Topic coverage ({coveredLeaves}/{totalLeaves} outline topics)</summary>
                    {#each sections as s}
                        {#if s.topics && s.topics.length}
                            <div class="topic-group">
                                <span class="topic-section">{s.abbrev}</span>
                                <div class="chips">
                                    {#each s.topics as t}
                                        <span
                                            class="chip {t.covered ? 'yes' : 'no'}"
                                            title="{t.title} - {t.covered ? 'covered' : 'not covered'}"
                                        >
                                            {t.code}
                                        </span>
                                    {/each}
                                </div>
                            </div>
                        {/if}
                    {/each}
                    <p class="muted topic-note">
                        Filled = a card covers this MCAT outline topic; outlined = not covered yet.
                        Readiness abstains below the coverage line, so uncovered topics can't hide
                        behind a confident score.
                    </p>
                </details>
            {:else}
                <p class="muted">No coverage data yet.</p>
            {/if}
        </section>

        <section class="panel">
            <h2>What to study next</h2>
                {#if plan.length}
                    <ol class="plan">
                        {#each plan as item}
                            <li class:prereq={item.prerequisite}>
                                <button
                                    class="plan-item"
                                    on:click={() => studyTopic(item.code)}
                                    title="Study {item.title}"
                                >
                                    <div class="plan-head">
                                        <span class="title">{item.title}</span>
                                        {#if item.prerequisite}
                                            <span class="prereq-badge">Foundational</span>
                                        {/if}
                                        <span class="plan-go">Study &rarr;</span>
                                    </div>
                                    <div class="reason">
                                        {item.prerequisite
                                            ? "Learn this before it blocks later topics."
                                            : "High-yield topic you're still weak on."}
                                    </div>
                                </button>
                            </li>
                        {/each}
                    </ol>
                {:else}
                    <p class="muted">Nothing to recommend yet - keep studying.</p>
                {/if}
        </section>
    </div>

    <section class="panel progress">
        <h2>Your progress</h2>
        <div class="scores">
            <div class="score">
                <div class="score-top">
                    <span class="score-label">Memory</span>
                    <span class="chip {memoryReading.tone}">{memoryReading.chip}</span>
                </div>
                {#if memAgg != null}
                    <div class="score-num">
                        {pct(memAgg)}
                        <span class="ev-unit">recall</span>
                    </div>
                {/if}
                {#if hasMemoryEvidence}
                    <div class="ev-sub">
                        calibrated to within {fmtPct(evidence?.memoryRmse)} over
                        {(evidence?.memoryReviews ?? 0).toLocaleString()} reviews
                    </div>
                {/if}
                <span class="score-body">{memoryReading.text}</span>
            </div>
            <div class="score">
                <div class="score-top">
                    <span class="score-label">Performance</span>
                    <span class="chip {performanceReading.tone}">{performanceReading.chip}</span>
                </div>
                {#if perfAgg != null}
                    <div class="score-num">
                        {pct(perfAgg)}
                        <span class="ev-unit">on exam-style questions</span>
                    </div>
                {/if}
                {#if hasPerfEvidence}
                    <div class="ev-sub">
                        model AUC {fmt(evidence?.perfAucFull)} vs {fmt(evidence?.perfAucRecall)} recall-only
                    </div>
                {/if}
                <span class="score-body">{performanceReading.text}</span>
            </div>
            <div class="score">
                <div class="score-top">
                    <span class="score-label">Readiness</span>
                    <span class="chip {readinessReading.tone}">{readinessReading.chip}</span>
                </div>
                {#if projected}
                    <div class="score-num">
                        {projected.score}
                        <span class="ev-unit">projected ({projected.low}&ndash;{projected.high})</span>
                    </div>
                {/if}
                <span class="score-body">{readinessReading.text}</span>
            </div>
        </div>
        <p class="fine">{totalReviews.toLocaleString()} reviews so far.</p>
    </section>

    {#if evidenceError}
        <div class="note">Could not load evidence: {evidenceError}</div>
    {/if}

    {#if showEvidence && evalResults}
        <section class="panel evidence">
            <h2>Evaluation evidence (spec 7 / 8 / 9 / 10)</h2>
            {#if !evalResults.available}
                <p class="muted">
                    No artifacts found. Run <code>just eval</code> (and <code>just bench</code> /
                    <code>just crash-test</code>) to generate them.
                </p>
            {/if}
            {#each evalResults.artifacts as a}
                <div class="ev-card">
                    <div class="ev-head">
                        <span class="ev-title">{a.title ?? a.name}</span>
                        {#if a.spec}<span class="ev-spec">{a.spec}</span>{/if}
                        {#if a.verdict}<span class="ev-verdict">{a.verdict}</span>{/if}
                    </div>
                    {#if a.model}
                        <div class="ev-meta">
                            model {a.model}{a.seed != null ? ` \u00b7 seed ${a.seed}` : ""}
                        </div>
                    {/if}
                    {#if a.summary}
                        <ul class="ev-summary">
                            {#each a.summary as line}<li>{@html md(line)}</li>{/each}
                        </ul>
                    {/if}
                    {#if a.table?.headers}
                        <div class="ev-table-wrap">
                            <table class="ev-table">
                                <thead>
                                    <tr>{#each a.table.headers as h}<th>{h}</th>{/each}</tr>
                                </thead>
                                <tbody>
                                    {#each a.table.rows as row}
                                        <tr>{#each row as cell}<td>{@html md(String(cell))}</td>{/each}</tr>
                                    {/each}
                                </tbody>
                            </table>
                        </div>
                    {/if}
                    {#if a.chart_svg}
                        <div class="ev-chart">{@html a.chart_svg}</div>
                    {/if}
                </div>
            {/each}
        </section>
    {/if}

</div>

<style lang="scss">
    // Match Anki's native web pages: theme CSS variables (light/dark aware), the
    // TitledContainer "card" look (elevated background, subtle border, underlined
    // title), and the shared radii/accents - no hardcoded colours.
    .speedrun {
        max-width: 880px;
        margin: 0 auto;
        padding: 12px 16px 24px;
        color: var(--fg);
        font-size: var(--font-size);
        line-height: 1.5;
    }

    .head {
        display: flex;
        align-items: baseline;
        justify-content: space-between;
        gap: 10px;

        h1 {
            margin: 6px 0 10px;
            font-size: 1.4em;
            font-weight: 600;
        }
    }

    .head-actions {
        display: flex;
        align-items: center;
        flex-wrap: wrap;
        gap: 8px;
    }

    // The primary call to action - starts a focused review of the next-best topic.
    .study-now {
        cursor: pointer;
        font: inherit;
        font-size: 0.9em;
        font-weight: 600;
        padding: 7px 16px;
        border-radius: var(--border-radius, 6px);
        border: 1px solid var(--button-primary-bg, var(--accent-card));
        background: var(--button-primary-bg, var(--accent-card));
        color: #fff;
        white-space: nowrap;

        // Keep an explicit primary background + white text on hover: relying on `filter`
        // alone let a base `button:hover` rule repaint it white, hiding the label.
        &:hover {
            background: var(--button-primary-bg, var(--accent-card));
            border-color: var(--button-primary-bg, var(--accent-card));
            color: #fff;
            filter: brightness(1.1);
        }
        &:focus-visible {
            outline: 2px solid var(--accent-card);
            outline-offset: 2px;
        }
    }

    .head-btn {
        cursor: pointer;
        font: inherit;
        font-size: 0.82em;
        padding: 5px 11px;
        border-radius: var(--border-radius, 5px);
        border: 1px solid var(--border-subtle);
        background: var(--button-bg, var(--canvas-elevated));
        color: var(--fg);
        white-space: nowrap;

        &.gear {
            padding: 5px 9px;
            font-size: 1em;
            line-height: 1;
        }
        &:hover {
            border-color: var(--accent-card);
        }
        &:focus-visible {
            outline: 2px solid var(--accent-card);
            outline-offset: 1px;
        }
    }

    // First-run onboarding card.
    .onboarding {
        margin: 14px 0 6px;
        padding: 18px 18px 20px;
        border: 1px solid var(--border-subtle);
        background: var(--canvas-elevated);
        border-radius: var(--border-radius-medium, 12px);

        h2 {
            margin: 0 0 6px;
            font-size: 1.15em;
        }
        p {
            margin: 0 0 12px;
            color: var(--fg-subtle);
            font-size: 0.92em;
            max-width: 52ch;
        }
        .study-now {
            font-size: 0.95em;
        }
    }

    .note {
        margin: 14px 0 4px;
        padding: 10px 12px;
        font-size: 0.9em;
        color: var(--fg-subtle);
        border: 1px solid var(--border-subtle);
        background: var(--canvas-elevated);
        border-radius: var(--border-radius-medium, 10px);
    }

    .panels {
        display: grid;
        grid-template-columns: 1fr;
        gap: 14px;
        margin-top: 14px;

        @media (min-width: 760px) {
            grid-template-columns: minmax(0, 1.05fr) minmax(0, 1fr);
            align-items: stretch;
        }
    }

    .progress {
        margin-top: 14px;
    }

    .panel {
        padding: 1rem 1.25rem 0.75rem;
        border: 1px solid var(--border-subtle);
        border-radius: var(--border-radius-medium, 10px);
        background: var(--canvas-elevated);

        h2 {
            margin: 0 0 12px;
            padding-bottom: 0.3em;
            font-size: 1.05em;
            font-weight: 600;
            color: var(--fg);
            border-bottom: 1px solid var(--border);
        }
    }

    .coverage-head {
        display: flex;
        flex-wrap: wrap;
        align-items: center;
        gap: 10px;

        .big {
            font-size: 2em;
            font-weight: 700;
            font-variant-numeric: tabular-nums;
        }
    }

    .cov-track {
        height: 8px;
        margin: 10px 0 2px;
        background: var(--canvas-inset);
        border-radius: var(--border-radius, 5px);
        overflow: hidden;
    }

    .cov-fill {
        display: block;
        height: 100%;
        background: var(--accent-card);
        border-radius: var(--border-radius, 5px);
        // Animates when the value updates (e.g. after a review), not on first paint.
        transition: width 320ms cubic-bezier(0.22, 1, 0.36, 1);
    }

    .leaves {
        margin: 4px 0 12px;
        color: var(--fg-subtle);
        font-size: 0.82em;
    }

    // Per-topic (content-category leaf) coverage breakdown (spec 7c).
    .topics {
        margin: 0 0 12px;
        font-size: 0.85em;
    }
    .topics summary {
        cursor: pointer;
        color: var(--fg-subtle);
        margin-bottom: 6px;
    }
    .topic-group {
        display: flex;
        align-items: baseline;
        gap: 8px;
        margin: 6px 0;
    }
    .topic-section {
        flex: 0 0 84px;
        font-weight: 600;
        color: var(--fg-subtle);
    }
    .chips {
        display: flex;
        flex-wrap: wrap;
        gap: 4px;
    }
    .chip {
        display: inline-block;
        padding: 1px 7px;
        border-radius: var(--border-radius, 5px);
        border: 1px solid var(--border-subtle);
        font-size: 0.85em;
    }
    .chip.yes {
        background: var(--button-primary-bg);
        border-color: var(--button-primary-bg);
        color: #fff;
    }
    .chip.no {
        color: var(--fg-subtle);
        opacity: 0.7;
    }
    .topic-note {
        margin-top: 8px;
    }

    // A quiet outlined chip (like a flag), tinted by the theme accent tokens.
    .pill {
        display: inline-block;
        padding: 2px 9px;
        border: 1px solid transparent;
        border-radius: var(--border-radius, 5px);
        font-size: 0.78em;
        font-weight: 600;
        white-space: nowrap;

        // Text uses --fg so the small label clears WCAG AA on the light card; the accent
        // stays as the border to carry the status hue (colored text was ~3:1).
        &.ok {
            color: var(--fg);
            border-color: var(--accent-note);
        }

        &.no {
            color: var(--fg);
            border-color: var(--accent-danger);
        }
    }

    table {
        width: 100%;
        border-collapse: collapse;
        font-size: 0.85em;
        table-layout: fixed;

        th,
        td {
            padding: 6px;
        }

        th {
            text-align: left;
            font-weight: 600;
            color: var(--fg-subtle);
            border-bottom: 1px solid var(--border);
        }

        td {
            border-top: 1px solid var(--border-subtle);
        }

        .section-cell {
            white-space: normal;
            overflow-wrap: anywhere;
            hyphens: auto;
        }

        .num {
            width: 3.4em;
            text-align: right;
            font-variant-numeric: tabular-nums;
        }

        .bar {
            width: 22%;

            .track {
                height: 8px;
                background: var(--canvas-inset);
                border-radius: var(--border-radius, 5px);
                overflow: hidden;
            }

            span {
                display: block;
                height: 100%;
                border-radius: var(--border-radius, 5px);
                background: var(--accent-card);
                transition: width 320ms cubic-bezier(0.22, 1, 0.36, 1);
            }
        }

        .dash {
            color: var(--fg-faint);
        }

        .num.mem {
            width: 5.4em;
        }

        .mem-point {
            display: block;
        }

        .mem-range {
            display: block;
            font-size: 0.8em;
            color: var(--fg-subtle);
            white-space: nowrap;
        }
    }

    .scores {
        display: grid;
        gap: 10px 18px;

        @media (min-width: 620px) {
            grid-template-columns: 1fr 1fr 1fr;
            align-items: start;
        }

        .score {
            display: grid;
            gap: 3px;
            font-size: 0.9em;
            align-content: start;
        }

        .score-top {
            display: flex;
            align-items: center;
            gap: 8px;
        }

        .score-label {
            font-weight: 700;
        }

        .score-body {
            color: var(--fg-subtle);
        }
    }

    // Status chip next to each score: honest "Locked" (with the reason in the body) until
    // there is data, "Tracking" once there is - never a fabricated number.
    .chip {
        padding: 1px 8px;
        border: 1px solid transparent;
        border-radius: var(--border-radius, 5px);
        font-size: 0.7em;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 0.3px;
        white-space: nowrap;

        // Text uses --fg (or --fg-subtle for the muted lock state) so the tiny uppercase
        // label clears WCAG AA in both themes; the accent stays as the border to keep the
        // status hue (the orange/green text was ~2.9-3.5:1).
        &.live {
            color: var(--fg);
            border-color: var(--accent-note);
        }

        &.lock {
            color: var(--fg-subtle);
            border-color: var(--border);
        }

        &.warn {
            color: var(--fg);
            border-color: var(--flag-2, #d9822b);
        }
    }

    .fine {
        margin: 12px 0 0;
        color: var(--fg-subtle);
        font-size: 0.75em;
    }

    .plan {
        display: grid;
        gap: 10px;
        margin: 0;
        padding-left: 20px;

        // Prereq reasons read at full --fg (regular reasons are --fg-subtle) so they stand
        // out and clear AA; the orange signal lives in the "Foundational" badge.
        li.prereq .reason {
            color: var(--fg);
        }
    }

    // Each plan row is a button that launches a focused study session for that topic.
    .plan-item {
        display: block;
        width: 100%;
        text-align: left;
        cursor: pointer;
        font: inherit;
        color: inherit;
        padding: 8px 10px;
        border: 1px solid var(--border-subtle);
        border-radius: var(--border-radius, 8px);
        background: var(--canvas-elevated);

        &:hover {
            border-color: var(--accent-card);
        }
        &:hover .plan-go {
            opacity: 1;
        }
        &:focus-visible {
            outline: 2px solid var(--accent-card);
            outline-offset: 1px;
        }
    }

    .plan-go {
        flex: 0 0 auto;
        font-size: 0.8em;
        font-weight: 600;
        color: var(--accent-card, var(--fg));
        opacity: 0.7;
        white-space: nowrap;
    }

    .plan-head {
        display: flex;
        align-items: flex-start;
        gap: 8px;

        .title {
            flex: 1 1 auto;
            min-width: 0;
            overflow-wrap: anywhere;
        }
    }

    .prereq-badge {
        padding: 0 5px;
        border: 1px solid var(--flag-2);
        border-radius: var(--border-radius, 5px);
        font-size: 0.7em;
        font-weight: 700;
        letter-spacing: 0.3px;
        text-transform: uppercase;
        white-space: nowrap;
        color: var(--fg);
    }

    .reason {
        margin-top: 2px;
        font-size: 0.82em;
        color: var(--fg-subtle);
    }

    .muted {
        margin: 4px 0 0;
        color: var(--fg-subtle);
        font-size: 0.88em;
    }

    .score-num {
        margin: 2px 0;
        font-size: 1.5em;
        font-weight: 700;
    }

    .ev-unit {
        font-size: 0.5em;
        font-weight: 500;
        color: var(--fg-subtle);
    }

    .ev-sub {
        margin-top: 2px;
        font-size: 0.76em;
        color: var(--fg-subtle);
    }

    .section-cell abbr {
        text-decoration: none;
        cursor: help;
    }

    // Drop the visual coverage-bar column on narrow screens (the % stays in the Covered
    // column) so the section label and Memory/Performance keep room.
    @media (max-width: 559px) {
        table .bar {
            display: none;
        }
    }

    @media (prefers-reduced-motion: reduce) {
        .cov-fill,
        table .bar span {
            transition: none;
        }
    }

    // -- In-app evidence view -------------------------------------------------
    .evidence-toggle {
        cursor: pointer;
        font: inherit;
        font-size: 0.82em;
        padding: 5px 11px;
        border-radius: var(--border-radius, 5px);
        border: 1px solid var(--border-subtle);
        background: var(--button-bg, var(--canvas-elevated));
        color: var(--fg);
        white-space: nowrap;

        &:hover {
            border-color: var(--accent-card);
        }

        &:focus-visible {
            outline: 2px solid var(--accent-card);
            outline-offset: 1px;
        }
    }

    .evidence {
        margin-top: 14px;

        .ev-card {
            padding: 10px 12px;
            margin: 10px 0;
            border: 1px solid var(--border-subtle);
            border-radius: var(--border-radius-medium, 10px);
            background: var(--canvas-inset, var(--canvas-elevated));
        }

        .ev-head {
            display: flex;
            flex-wrap: wrap;
            align-items: baseline;
            gap: 8px;
        }

        .ev-title {
            font-weight: 700;
        }

        .ev-spec {
            font-size: 0.78em;
            color: var(--fg-subtle);
        }

        .ev-verdict {
            margin-left: auto;
            font-size: 0.76em;
            font-weight: 600;
            color: var(--accent-note);
            border: 1px solid var(--accent-note);
            border-radius: var(--border-radius, 5px);
            padding: 1px 8px;
        }

        .ev-meta {
            font-size: 0.75em;
            color: var(--fg-faint);
            margin: 2px 0 6px;
        }

        .ev-summary {
            margin: 6px 0;
            padding-left: 18px;
            font-size: 0.9em;

            li {
                margin: 3px 0;
            }

            // Code spans come from {@html md(...)}, so Svelte can't see them to scope the
            // selector; :global keeps the style (scoped under .ev-summary) from being pruned.
            :global(code) {
                font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
                font-size: 0.9em;
            }
        }

        .ev-table-wrap {
            overflow-x: auto;
        }

        .ev-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.82em;
            margin: 6px 0;

            th,
            td {
                padding: 5px 8px;
                text-align: left;
                border-bottom: 1px solid var(--border-subtle);
            }

            th {
                color: var(--fg-subtle);
                font-weight: 600;
            }
        }

        .ev-chart {
            margin: 8px 0 2px;
            text-align: center;

            :global(svg) {
                max-width: 100%;
                height: auto;
            }
        }
    }
</style>
